# Generated by Django 5.0.6 on 2024-05-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAVs',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Model', models.CharField(max_length=500)),
                ('Brand', models.CharField(max_length=500)),
                ('Weight', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.area')),
                ('Dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealer.dealers')),
            ],
        ),
    ]
